### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by amnaarehman22** [jonathanrydholm/webgl-boilerplate#1]
I am starting the project, but I am getting this error. How can I solve it?
```
PS C:\Users\amnar\Documents\webgl-boilerplate> npm start      

> react-boilerplate@3.7.0 start
> cross-env NODE_ENV=development node server

Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3050
      LAN: http://192.168.0.218:3050
-----------------------------------
Press CTRL-C to stop
    
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\amnar\Documents\webgl-boilerplate\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\amnar\Documents\webgl-boilerplate\node_modules\webpack\lib\NormalModule.js:386:16)
    at handleParseError (C:\Users\amnar\Documents\webgl-boilerplate\node_modules\webpack\lib\NormalModule.js:434:10)
    at C:\Users\amnar\Documents\webgl-boilerplate\node_modules\webpack\lib\NormalModule.js:466:5
    at C:\Users\amnar\Documents\webgl-boilerplate\node_modules\webpack\lib\NormalModule.js:327:12
    at C:\Users\amnar\Documents\webgl-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\amnar\Documents\webgl-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (C:\Users\amnar\Documents\webgl-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:202:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by amnaarehman22** [comment]
I solved by adding : `export NODE_OPTIONS=--openssl-legacy-provider`

https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
